---
- name: Create dev Namespace
  k8s:
    name: "{{ dev_namespace }}"
    api_version: v1
    kind: Namespace
    definition:
      metadata:
        labels:
          app: "dev"
    state: present
  register: namespace_entry_result

- debug:
    msg: "{{ namespace_entry_result }}"
